# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: JS Presubmits

on:
  pull_request:
    paths:
      - "client/**"
    branches:
      - master

jobs:
  build_service_manager:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependencies
        working-directory: ./client/service-manager
        run: npm install

      - name: Lint JS
        working-directory: ./client/service-manager
        run: npm run lint

      - name: Run build
        working-directory: ./client/service-manager
        run: npm run build

      - name: Run test
        working-directory: ./client/service-manager
        run: npm test
        env:
          CI: true

  build_service_calculator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependencies
        working-directory: ./client/service-calculator
        run: npm install

      - name: Lint JS
        working-directory: ./client/service-calculator
        run: npm run lint

      - name: Run build
        working-directory: ./client/service-calculator
        run: npm run build

      - name: Run test
        working-directory: ./client/service-calculator
        run: npm test
        env:
          CI: true
