# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: API Presubmits

on:
  pull_request:
    paths:
      - "api/**"
      - "client/testing/mockRaw*.js"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # https://github.com/marketplace/actions/setup-php-action
      - name: Set up PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          extensions: intl

      - name: Start MySQL
        run: |
          sudo /etc/init.d/mysql start

      - name: Validate composer.json and composer.lock
        run: composer validate --working-dir=api

      - name: Install dependencies
        run: composer install --working-dir=api --prefer-dist --no-progress --no-suggest

      - name: Create doctrine database
        run: api/bin/console doctrine:database:create --env=test

      - name: Create doctrine schema
        run: api/bin/console doctrine:schema:create --env=test

      - name: Run test suite
        run: composer run-script --working-dir=api test

      - name: Start Dev Server
        run: php -S 127.0.0.1:8000 -d variables_order=EGPCS -t api/public &
        env:
          APP_ENV: test

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependencies
        working-directory: ./client/service-manager
        run: npm install

      - name: Check mock data
        run: composer test tests/ResetDatabase.php -d api && npm run check-mocks --prefix client/service-manager
